# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{beanpicker}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Renan Fernandes"]
  s.date = %q{2010-12-28}
  s.default_executable = %q{combine}
  s.description = %q{DSL for beanstalkd, similar to Stalker/Minion but uses subprocesses}
  s.email = %q{renan@kauamanga.com.br}
  s.executables = ["combine"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".rspec",
    "README.markdown",
    "Rakefile",
    "beanpicker.gemspec",
    "bin/combine",
    "examples/sandwich.rb",
    "lib/beanpicker.rb",
    "lib/beanpicker/job_server.rb",
    "lib/beanpicker/process.rb",
    "lib/beanpicker/version.rb",
    "spec/beanpicker_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ShadowBelmolve/beanpicker}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{DSL for beanstalkd, similar to Stalker/Minion}
  s.test_files = [
    "examples/sandwich.rb",
    "spec/beanpicker_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<beanstalk-client>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0"])
    else
      s.add_dependency(%q<beanstalk-client>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.0"])
    end
  else
    s.add_dependency(%q<beanstalk-client>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.0"])
  end
end

